import { renderProductPhase2AppHtml } from "./product-phase2-app.js";
import { PRODUCT_NAME } from "./brand.js";

const phase4Script = `<script>
(() => {
  const root = window.__citegeoPhase2;
  if (!root) return;
  const state = root.state;
  state.phase4 = { loading:false, action:"idle", reports:[], report:null, error:"", modelFilter:"all", evidence:null, competitorId:"" };
  const phase = state.phase4;
  const safeLink = (value) => { try { const parsed = new URL(value); return parsed.protocol === "https:" || parsed.protocol === "http:" ? parsed.toString() : ""; } catch { return ""; } };
  const statusText = (value) => value === "recognized" ? "Explicitly recognized" : value === "partially_recognized" ? "Partially recognized" : value === "unknown" ? "Unconfirmed in this run" : value === "ambiguous" ? "Ambiguous recognition in this run" : value === "not_recognized" ? "Explicitly did not recognize" : value === "analysis_failed" ? "Answer received, parsing failed" : value === "provider_failed" ? "Request failed in this run" : value === "unsupported" ? "Not supported by the current model or execution mode" : "Evidence integrity error";
  const fieldText = (value) => value === "reported" ? "Listed" : value === "not_reported" ? "Not listed in this run" : value === "analysis_failed" ? "Parsing failed" : value === "provider_failed" ? "Request failed" : value === "unsupported" ? "Not supported" : value === "entity_unresolved" ? "identity unconfirmed" : "Unconfirmed";
  const tag = (value) => '<span class="tag ' + (value === "recognized" ? "ready" : value === "provider_failed" || value === "analysis_failed" || value === "evidence_integrity_error" ? "warning" : "") + '">' + root.html("Recognition: " + statusText(value)) + '</span>';
  const selectedProject = () => root.project();
  const run = () => state.recognitionDetail && state.recognitionDetail.run ? state.recognitionDetail.run : null;
  const reportPath = () => { const selected = selectedProject(); const selectedRun = run(); return selected && selectedRun ? "/api/projects/" + encodeURIComponent(selected.id) + "/recognition-runs/" + encodeURIComponent(selectedRun.id) + "/reports" : ""; };
  const modelFor = (modelRunId) => phase.report ? phase.report.models.find((model) => model.modelRunId === modelRunId) || null : null;
  const allowedLink = (url, label) => { const safe = safeLink(url); return safe ? '<a href="' + root.html(safe) + '" target="_blank" rel="noreferrer noopener">' + root.html(label) + '</a>' : '<span class="subtle">Unsafe link hidden</span>'; };
  const evidenceHtml = (model, evidence, label) => {
    if (!evidence || evidence.integrity !== "valid" || !model.rawAnswer) return '<span class="subtle">No locatable evidence snippet</span>';
    return '<button type="button" class="evidence-jump" data-phase4-evidence-model="' + root.html(model.modelRunId) + '" data-phase4-evidence-start="' + evidence.evidence.start + '" data-phase4-evidence-end="' + evidence.evidence.end + '">' + root.html(label || "View evidence") + '</button>';
  };
  const renderRaw = (model) => {
    if (!model || !model.rawAnswer) return '<p class="subtle">This model has no raw answer to show.</p>';
    const evidence = phase.evidence && phase.evidence.modelRunId === model.modelRunId ? phase.evidence : null;
    if (!evidence) return '<pre class="raw-answer" data-testid="report-raw-answer">' + root.html(model.rawAnswer) + '</pre>';
    const answer = model.rawAnswer;
    const start = evidence.start;
    const end = evidence.end;
    if (start < 0 || end < start || end > answer.length) return '<pre class="raw-answer" data-testid="report-raw-answer">' + root.html(answer) + '</pre>';
    return '<pre class="raw-answer" data-testid="report-raw-answer">' + root.html(answer.slice(0, start)) + '<mark>' + root.html(answer.slice(start, end)) + '</mark>' + root.html(answer.slice(end)) + '</pre>';
  };
  const field = (title, claim, model) => '<div class="detail-cell"><span>' + root.html(title) + '</span><strong>' + root.html(claim && claim.value ? claim.value : "Unconfirmed") + '</strong>' + (claim ? evidenceHtml(model, claim.evidence, "View evidence") : "") + '</div>';
  const reportModelCard = (model) => {
    const unavailable = model.state === "analysis_failed" || model.state === "provider_failed" || model.state === "unsupported" || model.state === "evidence_integrity_error";
    const competitors = model.competitors === null ? '<p class="subtle">The competitor field could not be parsed, and must not be read as empty.</p>' : model.competitors.length ? '<ul>' + model.competitors.map((item) => '<li><strong>' + root.html(item.name) + '</strong>' + (item.domain ? ' · ' + root.html(item.domain) : ' · identity unconfirmed') + ' ' + evidenceHtml(model, item.evidence, "Evidence") + '</li>').join("") + '</ul>' : '<p class="subtle">No competitors listed in this run.</p>';
    const keywords = model.brandKeywords === null ? '<p class="subtle">The keyword field could not be parsed.</p>' : model.brandKeywords.length ? '<div class="inline-actions">' + model.brandKeywords.map((item) => '<span class="tag">' + root.html(item.keyword) + '</span>' + evidenceHtml(model, item.evidence, "Evidence")).join("") + '</div>' : '<p class="subtle">No target brand keywords were returned in this run.</p>';
    const retry = model.state === "analysis_failed" || model.state === "provider_failed" || model.state === "unsupported" ? '<button type="button" class="card-action" data-phase4-retry-model="' + root.html(model.modelRunId) + '">Retry this model</button>' : "";
    return '<article class="model-run-card" data-testid="report-model-card"><div class="model-run-head"><div><h3>' + root.html(model.displayName) + '</h3><p class="subtle">' + root.html(model.modelId) + ' · ' + root.html(model.webSearch.label) + '</p></div><div class="inline-actions">' + tag(model.state) + retry + '</div></div>' + (unavailable ? '<div class="warning-box">' + root.html(model.unavailableReason || "This model has no structured result available for the report.") + '</div>' : '<div class="detail-grid">' + field("Brand recognized by the model", model.recognizedBrand, model) + field("Business description", model.businessDescription, model) + field("Product category", model.productCategory, model) + '</div>') + '<div class="evidence-group"><h4>Competitors</h4>' + competitors + '</div><div class="evidence-group"><h4>Target brand keywords</h4>' + keywords + '</div><details class="evidence-details"><summary>View raw answer and technical evidence</summary><div class="evidence-group"><h4>Raw answer</h4>' + renderRaw(model) + '</div><div class="evidence-group"><h4>Raw provider response</h4><pre class="raw-answer">' + root.html(JSON.stringify(model.rawProviderResponse, null, 2)) + '</pre></div></details></article>';
  };
  const cell = (row, model) => { const entry = row.cells.find((item) => item.modelRunId === model.modelRunId); if (!entry) return '<td>Unconfirmed</td>'; const record = entry.recordIds.length ? ' <button type="button" class="evidence-jump" data-phase4-record="' + root.html(entry.recordIds[0]) + '">View evidence</button>' : ""; return '<td data-testid="report-matrix-cell">' + root.html(fieldText(entry.state)) + record + '</td>'; };
  const matrix = (title, rows, models, kind) => rows.length ? '<section class="section-card"><div class="section-head"><div><h2>' + root.html(title) + '</h2><p class="subtle">Each cell only shows whether that model returned the record in this run. It is not a market fact.</p></div></div><div class="matrix-wrap"><table class="matrix" data-testid="report-' + root.html(kind) + '-matrix"><thead><tr><th>Object</th>' + models.map((model) => '<th>' + root.html(model.displayName) + '</th>').join("") + '</tr></thead><tbody>' + rows.map((row) => '<tr><th>' + root.html(row.name || row.keyword) + (row.host ? '<span class="subtle">' + root.html(row.host) + '</span>' : "") + '</th>' + models.map((model) => cell(row, model)).join("") + '</tr>').join("") + '</tbody></table></div></section>' : '<section class="section-card"><h2>' + root.html(title) + '</h2><p class="subtle">No records to show for this run.</p></section>';
  const competitorKeywords = (report, models) => {
    const group = report.competitorGroups.find((item) => item.id === phase.competitorId) || report.competitorGroups[0] || null;
    if (!group) return '<section class="section-card"><h2>Competitor keywords</h2><p class="subtle">No competitor keywords in this run.</p></section>';
    const options = report.competitorGroups.map((item) => '<option value="' + root.html(item.id) + '">' + root.html(item.name + (item.host ? " · " + item.host : " · identity unconfirmed")) + '</option>').join("");
    const rows = [];
    for (const model of models) {
      const records = model.competitors || [];
      const groupRecordIds = new Set(group.sourceRecordIds);
      const selected = records.filter((record) => groupRecordIds.has(record.id));
      for (const record of selected) {
        const values = (model.competitorKeywords || []).filter((keyword) => keyword.competitorRecordId === record.id);
        for (const value of values) rows.push({ model, value, record });
      }
    }
    return '<section class="section-card"><div class="section-head"><div><h2>Competitor keywords</h2><p class="subtle">Keywords belong only to their own original competitor record and are never shared across objects.</p></div><select id="report-competitor-select" data-testid="report-competitor-select">' + options + '</select></div><div class="detail-grid">' + (rows.length ? rows.map((row) => '<div class="detail-cell"><span>' + root.html(row.model.displayName) + ' · ' + root.html(row.record.name) + '</span><strong>' + root.html(row.value.keyword) + '</strong>' + evidenceHtml(row.model, row.value.evidence, "View evidence") + '</div>').join("") : '<p class="subtle">This object has no keywords to show for this run.</p>') + '</div></section>';
  };
  const sources = (models) => '<section class="section-card"><div class="section-head"><div><h2>Sources</h2><p class="subtle">Provider citations are stored and shown separately from URLs in the answer body.</p></div></div><div class="source-columns"><div><h3>Provider Citation</h3>' + models.map((model) => { const values = model.providerCitations; return '<div class="evidence-group"><strong>' + root.html(model.displayName) + '</strong>' + (values === null ? '<p class="subtle">Could not be parsed</p>' : values.length ? '<ul>' + values.map((item) => '<li>' + allowedLink(item.url, item.title || item.domain) + '<span class="subtle"> · ' + root.html(item.providerPayloadPath) + '</span></li>').join("") + '</ul>' : '<p class="subtle">No provider citations were returned in this run.</p>') + '</div>'; }).join("") + '</div><div><h3>Answer body URLs</h3>' + models.map((model) => { const values = model.answerMentionedUrls; return '<div class="evidence-group"><strong>' + root.html(model.displayName) + '</strong>' + (values === null ? '<p class="subtle">Could not be parsed</p>' : values.length ? '<ul>' + values.map((item) => '<li>' + allowedLink(item.url, item.domain) + ' ' + evidenceHtml(model, item.evidence, "Evidence") + '</li>').join("") + '</ul>' : '<p class="subtle">No plain URLs in this run.</p>') + '</div>'; }).join("") + '</div></div></section>';
  const reportBody = () => {
    const report = phase.report;
    const selected = selectedProject();
    if (!selected) return '<section class="view"><div class="empty"><div class="empty-copy"><h2>Select a project first</h2></div></div></section>';
    if (phase.loading) return '<section class="view"><div class="empty"><div class="empty-copy"><h2>Loading the current report</h2><p class="subtle">Models are not called again.</p></div></div></section>';
    if (phase.error) return '<section class="view"><div class="warning-box"><strong>Cannot prepare the report</strong><p>' + root.html(phase.error) + '</p><button type="button" class="button" data-phase4-retry>Reload</button></div></section>';
    if (!report) return '<section class="view"><div class="empty"><div class="empty-copy"><h2>No recognition report to show yet</h2><p class="subtle">Once a recognition test finishes, the report is built from the fixed evidence of that run.</p></div></div></section>';
    const models = phase.modelFilter === "all" ? report.models : report.models.filter((model) => model.modelRunId === phase.modelFilter);
    const filters = '<button type="button" class="filter ' + (phase.modelFilter === "all" ? "active" : "") + '" data-phase4-model="all">All models</button>' + report.models.map((model) => '<button type="button" class="filter ' + (phase.modelFilter === model.modelRunId ? "active" : "") + '" data-phase4-model="' + root.html(model.modelRunId) + '">' + root.html(model.displayName) + '</button>').join("");
    const history = phase.reports.length > 1 ? '<select id="report-history" data-testid="report-history">' + phase.reports.map((item) => '<option value="' + root.html(item.reportId) + '" ' + (item.reportId === report.reportId ? "selected" : "") + '>Report version ' + item.reportRevision + ' · ' + root.html(root.formatTime(item.generatedAt)) + '</option>').join("") + '</select>' : '<span class="subtle">Report version ' + report.reportRevision + '</span>';
    const off = models.filter((model) => model.recognitionMode === "unaided_domain_recognition");
    const web = models.filter((model) => model.recognitionMode === "native_web_domain_discovery");
    const modelSummary = '<div class="detail-grid"><div class="detail-cell"><span>Models</span><strong>' + report.models.length + '</strong></div><div class="detail-cell"><span>Parsed</span><strong>' + report.models.filter((model) => model.state !== "analysis_failed" && model.state !== "provider_failed" && model.state !== "unsupported" && model.state !== "evidence_integrity_error").length + '</strong></div><div class="detail-cell"><span>Parsing failed</span><strong>' + report.models.filter((model) => model.state === "analysis_failed").length + '</strong></div><div class="detail-cell"><span>Request failed</span><strong>' + report.models.filter((model) => model.state === "provider_failed").length + '</strong></div></div>';
    return '<section class="view" data-testid="recognition-report"><div class="heading"><div><h1>Current recognition report</h1><p class="subtle">' + root.html(report.domain) + ' · ' + root.html(root.formatTime(report.generatedAt)) + ' · config v' + report.monitoringConfigurationVersion + '</p></div><div class="inline-actions">' + history + '<button type="button" class="button" data-phase4-refresh data-testid="refresh-report">Refresh report</button></div></div><div class="section-stack">' + modelSummary + '<section class="section-card"><div class="section-head"><div><h2>Model recognition</h2><p class="subtle">Each description reflects only this run\\'s answer. Offline recognition and live web findings are shown separately.</p></div></div><div class="toolbar">' + filters + '</div><h3>Offline domain recognition</h3><div class="model-run-list">' + (off.length ? off.map(reportModelCard).join("") : '<p class="subtle">No offline models in the current filter.</p>') + '</div><h3>Provider-native web findings</h3><div class="model-run-list">' + (web.length ? web.map(reportModelCard).join("") : '<p class="subtle">No web-enabled models in the current filter.</p>') + '</div></section>' + matrix("Competitors", report.competitorGroups, models, "competitor") + matrix("Target brand keywords", report.brandKeywordGroups, models, "keyword") + competitorKeywords(report, models) + sources(models) + '<section class="section-card"><h2>Technical details</h2><details><summary>View fixed sources and protocol</summary><pre class="raw-answer">' + root.html(JSON.stringify({ reportId:report.reportId, sourceAttemptMap:report.sourceAttemptMap, sourceRecordHashes:report.sourceRecordHashes, protocol:report.protocol, sourceFingerprint:report.sourceFingerprint }, null, 2)) + '</pre></details></section></div></section>';
  };
  const shell = () => { const selected = selectedProject(); const options = state.currentProjects.length ? state.currentProjects.map((item) => '<option value="' + root.html(item.id) + '">' + root.html(item.name) + ' · ' + root.html(item.normalizedDomain) + '</option>').join("") : '<option value="">No Project</option>'; root.app.innerHTML = '<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-lockup">' + root.brandLockup + '</div></div><div class="project-label">Project</div><select id="project-select" class="project-select" aria-label="Switch project" data-testid="project-select">' + options + '</select><nav class="nav" aria-label="Project navigation"><button type="button" class="nav-item" data-page="overview">Overview</button><button type="button" class="nav-item" data-page="models">AI Model</button><button type="button" class="nav-item" data-page="configuration">Configuration</button><button type="button" class="nav-item" data-page="setup">Setup</button><button type="button" class="nav-item" data-page="recognition">Domain recognition</button><button type="button" class="nav-item active" data-page="reports">Current report</button><button type="button" class="nav-item" data-phase5-open>Continuous measurement</button></nav><div class="sidebar-bottom">Current report</div></aside><main class="workspace"><header class="topbar"><div class="crumb"><strong>${PRODUCT_NAME}</strong> / ' + root.html(selected ? selected.name : "Project") + '</div><button id="new-project" type="button" class="button primary" data-testid="new-project">New project</button></header><section class="content">' + reportBody() + '</section></main></div>'; const select = root.element("project-select"); if (select) select.value = state.selectedId; };
  const loadReport = async (reportId) => { const path = reportPath(); if (!path) { phase.report = null; return; } const response = await root.request(path + "/" + encodeURIComponent(reportId)); phase.report = response.report; phase.competitorId = phase.competitorId || (phase.report.competitorGroups[0] ? phase.report.competitorGroups[0].id : ""); };
  const open = async () => { phase.loading = true; phase.error = ""; shell(); try { await root.refreshRecognition(); const path = reportPath(); if (!path) { phase.reports = []; phase.report = null; return; } const listed = await root.request(path); const created = await root.request(path, { method:"POST" }); const known = listed.reports || []; phase.reports = known.some((item) => item.reportId === created.report.reportId) ? known : [...known, created.report]; phase.reports.sort((left, right) => left.reportRevision - right.reportRevision); phase.report = created.report; phase.action = "idle"; } catch (error) { phase.error = error instanceof Error ? error.message : "Request did not complete"; } finally { phase.loading = false; shell(); } };
  const findEvidence = (recordId) => { if (!phase.report) return null; for (const model of phase.report.models) { const competitor = (model.competitors || []).find((item) => item.id === recordId); if (competitor && competitor.evidence.integrity === "valid") return { modelRunId:model.modelRunId, start:competitor.evidence.evidence.start, end:competitor.evidence.evidence.end }; const brand = (model.brandKeywords || []).find((item) => item.id === recordId); if (brand && brand.evidence.integrity === "valid") return { modelRunId:model.modelRunId, start:brand.evidence.evidence.start, end:brand.evidence.evidence.end }; } return null; };
  window.__citegeoPhase4 = { render:shell, open };
  document.addEventListener("click", async (event) => { const target = event.target; if (!(target instanceof Element)) return; const measurement = target.closest("[data-phase5-open]"); if (measurement) { const next = new URL(window.location.href); const selected = selectedProject(); next.searchParams.set("view", "measurements"); if (selected) next.searchParams.set("project", selected.id); window.location.assign(next.toString()); return; } const filter = target.closest("[data-phase4-model]"); if (filter) { phase.modelFilter = filter.getAttribute("data-phase4-model") || "all"; shell(); return; } if (target.closest("[data-phase4-refresh]") || target.closest("[data-phase4-retry]")) { if (!phase.loading) await open(); return; } const retryModel = target.closest("[data-phase4-retry-model]"); if (retryModel) { const selected = selectedProject(); const selectedRun = run(); const runId = phase.report ? phase.report.runId : selectedRun ? selectedRun.id : ""; const modelRunId = retryModel.getAttribute("data-phase4-retry-model"); if (!selected || !runId || !modelRunId || phase.action === "loading") return; phase.action = "loading"; retryModel.setAttribute("data-action-state", "loading"); retryModel.textContent = "Retrying…"; try { await root.request("/api/projects/" + encodeURIComponent(selected.id) + "/recognition-runs/" + encodeURIComponent(runId) + "/model-runs/" + encodeURIComponent(modelRunId) + "/retry", { method:"POST" }); state.recognitionSelectedRunId = runId; await root.refreshRecognition(); await open(); } catch (error) { phase.error = error instanceof Error ? error.message : "Retry failed"; shell(); } finally { phase.action = "idle"; } return; } const evidence = target.closest("[data-phase4-evidence-model]"); if (evidence) { phase.evidence = { modelRunId:evidence.getAttribute("data-phase4-evidence-model") || "", start:Number(evidence.getAttribute("data-phase4-evidence-start")), end:Number(evidence.getAttribute("data-phase4-evidence-end")) }; shell(); const raw = document.querySelector("[data-testid=report-raw-answer] mark"); if (raw) raw.scrollIntoView({ block:"center", behavior:"smooth" }); return; } const record = target.closest("[data-phase4-record]"); if (record) { phase.evidence = findEvidence(record.getAttribute("data-phase4-record") || ""); shell(); return; } });
  document.addEventListener("change", async (event) => { const target = event.target; if (!(target instanceof HTMLSelectElement)) return; if (target.id === "report-history") { await loadReport(target.value); shell(); return; } if (target.id === "report-competitor-select") { phase.competitorId = target.value; shell(); } });
})();
</script>`;

export function renderProductPhase4AppHtml(): string {
  return renderProductPhase2AppHtml().replace("</body>", `${phase4Script}</body>`);
}
