import { GitHubClient } from "./github-client.js";
import { buildFixPlan } from "./fix-plan.js";
import type { FixPlan } from "./fix-plan.js";
import type { SiteSignals } from "../actions/site-signals.js";
import type { GeoAction } from "../actions/action-plan.js";

// Opens one pull request carrying the patches, and describing everything it
// could not patch. The description is the point: a reviewer should be able to
// see the evidence behind each change without opening this tool.

export interface FixPullRequestResult {
  outcome: "opened" | "nothing_to_do" | "failed";
  detail: string;
  url?: string | undefined;
  plan?: FixPlan | undefined;
}

export function pullRequestBody(input: { plan: FixPlan; domain: string; checkedAt: string }): string {
  const lines = [
    `Generated by CiteGEO from a site probe of ${input.domain} on ${input.checkedAt.slice(0, 10)}.`,
    "",
    "Every item below names the observation behind it. Nothing here was inferred from a model's opinion.",
    "",
  ];

  if (input.plan.patches.length) {
    lines.push("## Changed in this pull request", "");
    for (const patch of input.plan.patches) lines.push(`- **\`${patch.path}\`** ${patch.summary}`);
    lines.push("");
  }

  if (input.plan.manual.length) {
    lines.push("## Not changed here, and why", "");
    for (const item of input.plan.manual) {
      lines.push(`### ${item.title}`, "", `- Observed: ${item.evidence}`, `- Fix: ${item.fix}`, `- Why not automated: ${item.reason}`, "");
    }
  }

  lines.push(
    "## Before merging",
    "",
    "- Read the diff. This was generated, so it deserves the same scrutiny as any other generated change.",
    "- An `llms.txt` added here has a placeholder description. Write it before merging, because an answer engine will quote it.",
    "",
  );
  return lines.join("\n");
}

export async function openFixPullRequest(input: {
  client: GitHubClient;
  signals: SiteSignals;
  actions: GeoAction[];
  brand: string;
  categories?: string[] | undefined;
  now?: Date;
}): Promise<FixPullRequestResult> {
  const at = input.now || new Date();
  try {
    const base = await input.client.defaultBranch();
    // Read robots.txt first so it is edited rather than replaced, since it
    // carries rules this tool knows nothing about.
    const existingRobots = await input.client.readFile("robots.txt", base);

    const plan = buildFixPlan({
      signals: input.signals,
      actions: input.actions,
      brand: input.brand,
      ...(input.categories ? { categories: input.categories } : {}),
      ...(existingRobots ? { robotsTxt: existingRobots.contents } : {}),
    });

    if (!plan.worthOpening) {
      return { outcome: "nothing_to_do", detail: "Nothing outstanding that a pull request could carry.", plan };
    }
    if (!plan.patches.length) {
      // Opening a pull request with no diff would be noise. The findings are
      // still returned so the caller can show them.
      return {
        outcome: "nothing_to_do",
        detail: `${plan.manual.length} finding(s), none of which can be fixed by changing a file in this repository.`,
        plan,
      };
    }

    const branch = `citegeo/site-fixes-${at.toISOString().slice(0, 10)}-${at.getTime().toString(36)}`;
    await input.client.createBranch(branch, base);

    for (const patch of plan.patches) {
      const existing = patch.path === "robots.txt" ? existingRobots : await input.client.readFile(patch.path, base);
      await input.client.putFile({
        path: patch.path,
        contents: patch.contents,
        branch,
        message: `${patch.path}: ${patch.summary}`,
        ...(existing ? { sha: existing.sha } : {}),
      });
    }

    const url = await input.client.openPullRequest({
      head: branch,
      base,
      title: `Site fixes for answer engines (${plan.patches.length} file${plan.patches.length === 1 ? "" : "s"})`,
      body: pullRequestBody({ plan, domain: input.signals.domain, checkedAt: at.toISOString() }),
    });
    return { outcome: "opened", detail: `Opened with ${plan.patches.length} file change(s).`, url, plan };
  } catch (error) {
    return { outcome: "failed", detail: error instanceof Error ? error.message : String(error) };
  }
}
